version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: aq54db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nest-app:
    build:
      context: ./aq54
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: mydatabase

  react-app:
    build:
      context: ./aq54-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

volumes:
  pgdata:
